INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./experiments"

# Evaluation datasets
GRABCUT_PATH: "./data/GrabCut"
BERKELEY_PATH: "./data/Berkeley"
DAVIS_PATH: "./data/DAVIS"
COCO_MVAL_PATH: "./data/COCO_MVal"

# Train datasets
SBD_PATH: "/workspace/data/sbd/dataset"

# <FSS>
SBD_PATH_2: "/workspace/data/VOCdevkit/VOC2012"
SBD_TRAIN_LIST: "/workspace/data/lists/pascal/sbd_data.txt"
SBD_VAL_LIST: "/workspace/data/lists/pascal/val.txt"
# </FSS>

COCO_PATH: "./data/coco2017"
LVIS_PATH: "./data/LVIS"
OPENIMAGES_PATH: "./data/OpenImages"
PASCALVOC_PATH: "./data/PascalVOC"
ADE20K_PATH: "./data/ADE20K"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
